# frozen_string_literal: true

require "test_helper"
require "ruby_ui_admin/tailwind_source"

module RubyUIAdmin
  class TailwindSourceTest < ActiveSupport::TestCase
    test "extracts class tokens from string literals" do
      tokens = TailwindSource.extract('div(class: "text-sm flex mb-6"); a(class: %(font-medium))')

      assert_includes tokens, "text-sm"
      assert_includes tokens, "flex"
      assert_includes tokens, "mb-6"
    end

    test "drops #{} interpolations but keeps the literal fragments around them" do
      # single-quoted so the test source itself doesn't interpolate.
      tokens = TailwindSource.extract('span(class: "#{svg_classes} -ml-px size-4")')

      assert_includes tokens, "-ml-px"
      assert_includes tokens, "size-4"
      refute(tokens.any? { |t| t.include?("#") || t.include?("{") })
      refute_includes tokens, "svg_classes"
    end

    test "keeps utilities with variants and arbitrary values, rejects prose" do
      tokens = TailwindSource.extract('x(class: "hover:bg-foreground/10 w-[356px] sm:grid-cols-2"); t("Are you sure?")')

      assert_includes tokens, "hover:bg-foreground/10"
      assert_includes tokens, "w-[356px]"
      assert_includes tokens, "sm:grid-cols-2"
      refute_includes tokens, "Are"
      refute_includes tokens, "sure?"
    end

    test "class_candidates scans the real engine views and finds known classes" do
      candidates = TailwindSource.class_candidates

      refute_empty candidates
      assert_includes candidates, "sr-only" # present in the engine's views
    end

    test "html wraps the candidates in a scannable div and write persists it" do
      dir = Dir.mktmpdir
      dest = File.join(dir, "ruby_ui_admin_classes.html")

      returned = TailwindSource.write(dest)

      assert_equal dest, returned
      body = File.read(dest)
      assert_match(/<div class="/, body)
      assert_match "sr-only", body
      assert_match "Generated by", body
    ensure
      FileUtils.remove_entry(dir) if dir
    end
  end
end
